sudo: true
language: ruby
rvm:
  - 2.6.0
  - 2.5.3
  - 2.4.5
  - 2.3.8
cache: bundler
script: bundle exec rspec
after_success: coveralls

before_install:
  - sudo add-apt-repository -y ppa:chris-lea/libsodium
  - sudo apt-get update -q
  - sudo apt-get install libsodium-dev
